### ISSUE TITLE
Getting "out of cheese error" while running a sparql query against http://nidm.scicrunch.io

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/ReproLake-misc#1]
I have not found a good venue to complain, so I created a new one, I hope you don't mind

Brought to you by @surchs !

![image](https://user-images.githubusercontent.com/39889/124180911-d808ef80-da82-11eb-9933-64a0b18287a2.png)

is that a user error or something which could be tuned up on that secret instance?

attn @dbkeator @jgrethe 

https://github.com/dasch-swiss/dsp-api/issues/956 might be related and suggests an upgrade

**Comment by bcalvignac** [comment]
Same problem on GraphDB 10.0 (free version). Does not seem to happen on the Enterprise version

**Comment by jgrethe** [comment]
We are transitioning to StarDog and verified that this query is working (saved query in StarDog T1-Weighted-OpenNeuro-Data).
